name: eurovision
version: 0.1.0.0
github: "githubuser/eurovision"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/eurovision#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - monad-logger
  - persistent
  - persistent-template
  - persistent-sqlite
  - servant
  - servant-server
  - servant-client
  - string-conversions
  - text
  - transformers
  - wai
  - warp
  - hspec
  - http-client
  - mockery
  - http-types

library:
  source-dirs: lib

executables:
  eurovision:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - eurovision

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    other-modules:
      - App
      - Api
      - Models
      - AppSpec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - eurovision
